/* Gesundheits-App — Wissen: Vitamine & Nährstoffe
   © 2026 Marcel Fehse. Alle Rechte vorbehalten.

   Faktenbasiert (Orientierung DGE/EFSA). Mengen sind grobe Richtwerte für gesunde
   Erwachsene und ersetzen keine ärztliche Beratung. */

(function (root) {
  const N = (id, name, emoji, grad, type, short, role, sources, need, deficiency, tips, combos) =>
    ({ id, name, emoji, grad, type, short, role, sources, need, deficiency, tips, combos: combos || null });

  const nutrients = [
    N('vitd', 'Vitamin D3', '☀️', 'amber', 'Vitamin',
      'Das „Sonnenvitamin" für Knochen & Immunsystem.',
      'Vitamin D3 (Cholecalciferol) hilft, Calcium aufzunehmen, hält Knochen und Zähne stark und unterstützt das Immunsystem. Der Körper bildet es selbst über Sonnenlicht auf der Haut. D3 ist die Form, die der Körper am besten verwertet.',
      ['Sonnenlicht (wichtigste Quelle)', 'fetter Fisch (Hering, Lachs)', 'Eier', 'angereicherte Margarine'],
      'ca. 20 µg/Tag, wenn kaum Sonne',
      'Im Winter oft zu niedrig. Mögliche Folgen: müde Knochen, häufige Infekte.',
      ['Im Winter (Okt–März) ist ein Mangel in Deutschland verbreitet.', 'Supplement nur faktenbasiert und in Maßen – bei Unsicherheit Blutwert prüfen lassen.'],
      ['Vitamin K2: D3 holt Calcium ins Blut, K2 lenkt es in die Knochen statt in die Gefäße. Bei höher dosiertem D3 fast immer zusammen empfohlen.',
       'Magnesium: wird gebraucht, um Vitamin D im Körper überhaupt zu aktivieren – ohne genug Magnesium wirkt D3 schwächer.',
       'Etwas Fett zur Mahlzeit: D3 ist fettlöslich und wird mit Fett deutlich besser aufgenommen.',
       'Calcium: D3 verbessert die Calcium-Aufnahme – gut für die Knochen.']),
    N('b12', 'Vitamin B12', '🧬', 'terracotta', 'Vitamin',
      'Wichtig für Blut, Nerven & Energie.',
      'B12 wird für die Blutbildung, die Nerven und den Energiestoffwechsel gebraucht. Es kommt fast nur in tierischen Lebensmitteln vor.',
      ['Eier', 'Milch & Käse', 'Fleisch & Fisch', 'angereicherte Pflanzendrinks'],
      'ca. 4 µg/Tag',
      'Bei rein pflanzlicher Ernährung ohne Supplement drohen Müdigkeit, Blutarmut, Nervenprobleme.',
      ['Wer vegan lebt, sollte B12 supplementieren – das ist medizinischer Konsens, keine Meinung.', 'Vegetarier decken es meist über Eier und Milchprodukte.']),
    N('vitc', 'Vitamin C', '🍊', 'sunrise', 'Vitamin',
      'Immunsystem & bessere Eisenaufnahme.',
      'Vitamin C schützt die Zellen, unterstützt das Immunsystem und verbessert die Aufnahme von pflanzlichem Eisen deutlich.',
      ['Paprika', 'Brokkoli', 'Zitrusfrüchte', 'Beeren', 'Kartoffeln'],
      'ca. 95–110 mg/Tag',
      'Sehr selten (Skorbut). Eher relevant: zu wenig Obst/Gemüse generell.',
      ['Mit Eisenquellen kombinieren: Linsen + Paprika = bessere Eisenaufnahme.', 'Hitze zerstört Vitamin C – Gemüse schonend garen.'],
      ['Eisen: Vitamin C macht pflanzliches Eisen (Linsen, Spinat) für den Körper viel besser verfügbar – einfach Paprika oder Zitrone dazu.']),
    N('vita', 'Vitamin A', '🥕', 'amber', 'Vitamin',
      'Augen, Haut & Schleimhäute.',
      'Vitamin A ist wichtig für das Sehen (besonders bei Dämmerung), gesunde Haut und Schleimhäute. Der Körper bildet es auch aus Beta-Carotin aus buntem Gemüse.',
      ['Möhren', 'Süßkartoffeln', 'Spinat', 'Eier', 'Butter'],
      'ca. 0,8–1 mg/Tag',
      'Selten in DE. Mangel kann Nachtblindheit und trockene Haut verursachen.',
      ['Beta-Carotin aus Möhren wird mit etwas Fett (z. B. Öl) besser aufgenommen.'],
      ['Etwas Fett: Vitamin A ist fettlöslich – Möhren mit einem Schuss Öl liefern viel mehr.']),
    N('vite', 'Vitamin E', '🌻', 'sage', 'Vitamin',
      'Zellschutz (Antioxidans).',
      'Vitamin E schützt die Zellen vor schädlichen Einflüssen und unterstützt die Zellmembranen.',
      ['Pflanzenöle', 'Nüsse', 'Samen', 'Vollkorn'],
      'ca. 11–15 mg/Tag',
      'Mangel ist selten bei normaler Ernährung.',
      ['Eine Handvoll Nüsse am Tag deckt viel ab und sättigt gut.'],
      ['Etwas Fett: auch Vitamin E ist fettlöslich – aus Nüssen und Pflanzenöl ohnehin gut verfügbar.']),
    N('vitk', 'Vitamin K2', '🥬', 'sage', 'Vitamin',
      'Lenkt Calcium in die Knochen statt in die Gefäße.',
      'Vitamin K wird für die Blutgerinnung und gesunde Knochen gebraucht. K1 steckt in grünem Gemüse, K2 aktiviert die Eiweiße, die Calcium in die Knochen einbauen – statt in die Arterien. Genau deshalb ist K2 der ideale Partner zu Vitamin D3.',
      ['grünes Blattgemüse (K1)', 'Brokkoli', 'Spinat', 'Käse & Natto (K2)', 'Eier (K2)'],
      'ca. 60–80 µg/Tag',
      'Mangel selten. Hinweis: Bei blutverdünnenden Medikamenten (z. B. Marcumar) unbedingt mit Arzt abstimmen.',
      ['Grünes Gemüse mehrmals pro Woche deckt den Grundbedarf locker.', 'K2 (z. B. aus Käse, Natto) ist die für Knochen & Gefäße entscheidende Form.'],
      ['Vitamin D3: das klassische Duo – D3 sorgt für Calcium, K2 bringt es an die richtige Stelle (Knochen statt Gefäße).',
       'Etwas Fett zur Mahlzeit: K2 ist fettlöslich und wird mit Fett besser aufgenommen.']),
    N('bgroup', 'B-Vitamine (B1/B2/B6)', '🌾', 'amber', 'Vitamin',
      'Energie aus dem Essen gewinnen.',
      'Die B-Vitamine helfen, aus Nahrung Energie zu gewinnen, und unterstützen Nerven und Stoffwechsel.',
      ['Vollkorn', 'Hülsenfrüchte', 'Kartoffeln', 'Eier', 'Milchprodukte'],
      'je nach Vitamin 1–2 mg/Tag',
      'Bei einseitiger Ernährung möglich: Müdigkeit, Konzentrationsprobleme.',
      ['Vollkorn statt Weißmehl liefert deutlich mehr B-Vitamine.']),
    N('folate', 'Folsäure (B9)', '🥦', 'sage', 'Vitamin',
      'Zellteilung – besonders in der Schwangerschaft.',
      'Folsäure ist wichtig für Zellteilung und Blutbildung und besonders vor/in der Schwangerschaft entscheidend.',
      ['Brokkoli', 'Spinat', 'Hülsenfrüchte', 'Vollkorn'],
      'ca. 300 µg/Tag (Schwangere mehr)',
      'Mangel kann Blutarmut verursachen; in der Schwangerschaft Risiko für das Kind.',
      ['Schwangere oder Frauen mit Kinderwunsch: ärztlich beraten lassen (oft Supplement empfohlen).']),
    N('iron', 'Eisen', '🩸', 'terracotta', 'Mineralstoff',
      'Sauerstofftransport im Blut.',
      'Eisen transportiert Sauerstoff im Blut. Pflanzliches Eisen (z. B. aus Linsen) nimmt der Körper schlechter auf als tierisches – Vitamin C hilft dabei.',
      ['Linsen', 'Bohnen', 'Haferflocken', 'Spinat', 'rotes Fleisch'],
      'Frauen ca. 15 mg, Männer ca. 10 mg/Tag',
      'Häufig bei Frauen: Müdigkeit, Blässe, Konzentrationsschwäche.',
      ['Eisen + Vitamin C kombinieren (Linsen + Paprika).', 'Kaffee & Tee hemmen die Aufnahme – erst ~1 Std. nach dem Essen trinken.'],
      ['Vitamin C: bester Partner – verbessert die Aufnahme von pflanzlichem Eisen deutlich.',
       'NICHT mit Calcium zusammen: Calcium (Milchprodukte) bremst die Eisenaufnahme – zeitlich trennen.',
       'NICHT mit Kaffee/Tee: hemmen Eisen – ca. 1 Stunde Abstand halten.']),
    N('calcium', 'Calcium', '🦴', 'peach', 'Mineralstoff',
      'Starke Knochen & Zähne.',
      'Calcium ist der wichtigste Baustein für Knochen und Zähne und wird auch für Muskeln und Nerven gebraucht.',
      ['Milch & Joghurt', 'Käse', 'grünes Gemüse', 'calciumreiches Mineralwasser'],
      'ca. 1000 mg/Tag',
      'Langfristiger Mangel schwächt die Knochen.',
      ['Wer keine Milch verträgt: grünes Gemüse + angereicherte Pflanzendrinks nutzen.', 'Vitamin D hilft, Calcium aufzunehmen.'],
      ['Vitamin D3: nötig, damit der Körper Calcium überhaupt aufnimmt.',
       'Vitamin K2: lenkt das Calcium in die Knochen statt in die Gefäße – ideales Trio D3 + K2 + Calcium.',
       'NICHT mit Eisen-Präparaten gleichzeitig: bremst die Eisenaufnahme – zeitlich trennen.']),
    N('magnesium', 'Magnesium', '⚡', 'sage', 'Mineralstoff',
      'Muskeln, Nerven & Energie.',
      'Magnesium unterstützt Muskeln und Nerven und ist an sehr vielen Stoffwechsel-Vorgängen beteiligt.',
      ['Vollkorn', 'Nüsse', 'Hülsenfrüchte', 'Bananen', 'dunkle Schokolade'],
      'ca. 300–400 mg/Tag',
      'Möglich bei Sport/Schwitzen: Muskelkrämpfe, Müdigkeit.',
      ['Nach dem Sport hilft eine magnesiumreiche Mahlzeit (z. B. Haferflocken mit Nüssen).'],
      ['Vitamin D3: Magnesium aktiviert Vitamin D im Körper – ohne genug Magnesium wirkt D3 schwächer.',
       'Calcium: Magnesium und Calcium arbeiten im Muskel zusammen (Anspannen ↔ Entspannen).']),
    N('zinc', 'Zink', '🛡️', 'amber', 'Mineralstoff',
      'Immunsystem & Wundheilung.',
      'Zink unterstützt Immunsystem, Wundheilung sowie Haut und Haare.',
      ['Vollkorn', 'Hülsenfrüchte', 'Käse', 'Fleisch', 'Kürbiskerne'],
      'ca. 7–10 mg/Tag',
      'Mangel kann Immunschwäche und schlechte Wundheilung bedeuten.',
      ['Pflanzliche Quellen + tierisches Eiweiß verbessern die Aufnahme.']),
    N('iodine', 'Jod', '🧂', 'sunrise', 'Mineralstoff',
      'Schilddrüse & Stoffwechsel.',
      'Jod ist nötig für die Schilddrüsenhormone, die den ganzen Stoffwechsel steuern.',
      ['Jodsalz', 'Seefisch', 'Milchprodukte', 'Algen (vorsichtig dosieren)'],
      'ca. 200 µg/Tag',
      'Deutschland ist Jodmangel-Gebiet – Mangel kann die Schilddrüse vergrößern.',
      ['Im Haushalt Jodsalz verwenden – einfachster Schutz vor Mangel.']),
    N('omega3', 'Omega-3-Fettsäuren', '🐟', 'sage', 'Fettsäure',
      'Herz, Gehirn & Entzündungen.',
      'Omega-3-Fettsäuren unterstützen Herz und Gehirn und wirken entzündungsregulierend.',
      ['fetter Fisch (Lachs, Hering)', 'Leinöl & Leinsamen', 'Walnüsse', 'Rapsöl'],
      '1–2× fetter Fisch/Woche oder pflanzliche Quellen täglich',
      'Bei sehr fettarmer/einseitiger Kost möglich.',
      ['Vegetarisch/vegan: Leinöl, Leinsamen und Walnüsse einplanen.']),
    N('fiber', 'Ballaststoffe', '🌿', 'sage', 'Sonstiges',
      'Verdauung & lange Sättigung.',
      'Ballaststoffe halten die Verdauung in Schwung, sättigen lange und füttern die guten Darmbakterien.',
      ['Vollkorn', 'Hülsenfrüchte', 'Gemüse', 'Obst', 'Haferflocken'],
      'mind. 30 g/Tag',
      'Zu wenig führt oft zu träger Verdauung und schnellem Hunger.',
      ['Langsam steigern und genug trinken, sonst drückt der Bauch.']),
  ];

  const GKNOW = { nutrients };
  if (typeof window !== 'undefined') window.GKNOW = GKNOW;
  if (typeof module !== 'undefined' && module.exports) module.exports = GKNOW;
})(typeof window !== 'undefined' ? window : globalThis);
