/* Gesundheits-App — Wissen: Vitamine & Nährstoffe
   © 2026 Marcel Fehse. Alle Rechte vorbehalten.

   Faktenbasiert (Orientierung DGE/EFSA). Mengen sind grobe Richtwerte für gesunde
   Erwachsene und ersetzen keine ärztliche Beratung. */

(function (root) {
  const N = (id, name, emoji, grad, type, short, role, sources, need, deficiency, tips) =>
    ({ id, name, emoji, grad, type, short, role, sources, need, deficiency, tips });

  const nutrients = [
    N('vitd', 'Vitamin D', '☀️', 'amber', 'Vitamin',
      'Das „Sonnenvitamin" für Knochen & Immunsystem.',
      'Vitamin D hilft, Calcium aufzunehmen, hält Knochen und Zähne stark und unterstützt das Immunsystem. Der Körper bildet es selbst über Sonnenlicht auf der Haut.',
      ['Sonnenlicht (wichtigste Quelle)', 'fetter Fisch (Hering, Lachs)', 'Eier', 'angereicherte Margarine'],
      'ca. 20 µg/Tag, wenn kaum Sonne',
      'Im Winter oft zu niedrig. Mögliche Folgen: müde Knochen, häufige Infekte.',
      ['Im Winter (Okt–März) ist ein Mangel in Deutschland verbreitet.', 'Supplement nur faktenbasiert und in Maßen – bei Unsicherheit Blutwert prüfen lassen.']),
    N('b12', 'Vitamin B12', '🧬', 'terracotta', 'Vitamin',
      'Wichtig für Blut, Nerven & Energie.',
      'B12 wird für die Blutbildung, die Nerven und den Energiestoffwechsel gebraucht. Es kommt fast nur in tierischen Lebensmitteln vor.',
      ['Eier', 'Milch & Käse', 'Fleisch & Fisch', 'angereicherte Pflanzendrinks'],
      'ca. 4 µg/Tag',
      'Bei rein pflanzlicher Ernährung ohne Supplement drohen Müdigkeit, Blutarmut, Nervenprobleme.',
      ['Wer vegan lebt, sollte B12 supplementieren – das ist medizinischer Konsens, keine Meinung.', 'Vegetarier decken es meist über Eier und Milchprodukte.']),
    N('vitc', 'Vitamin C', '🍊', 'sunrise', 'Vitamin',
      'Immunsystem & bessere Eisenaufnahme.',
      'Vitamin C schützt die Zellen, unterstützt das Immunsystem und verbessert die Aufnahme von pflanzlichem Eisen deutlich.',
      ['Paprika', 'Brokkoli', 'Zitrusfrüchte', 'Beeren', 'Kartoffeln'],
      'ca. 95–110 mg/Tag',
      'Sehr selten (Skorbut). Eher relevant: zu wenig Obst/Gemüse generell.',
      ['Mit Eisenquellen kombinieren: Linsen + Paprika = bessere Eisenaufnahme.', 'Hitze zerstört Vitamin C – Gemüse schonend garen.']),
    N('vita', 'Vitamin A', '🥕', 'amber', 'Vitamin',
      'Augen, Haut & Schleimhäute.',
      'Vitamin A ist wichtig für das Sehen (besonders bei Dämmerung), gesunde Haut und Schleimhäute. Der Körper bildet es auch aus Beta-Carotin aus buntem Gemüse.',
      ['Möhren', 'Süßkartoffeln', 'Spinat', 'Eier', 'Butter'],
      'ca. 0,8–1 mg/Tag',
      'Selten in DE. Mangel kann Nachtblindheit und trockene Haut verursachen.',
      ['Beta-Carotin aus Möhren wird mit etwas Fett (z. B. Öl) besser aufgenommen.']),
    N('vite', 'Vitamin E', '🌻', 'sage', 'Vitamin',
      'Zellschutz (Antioxidans).',
      'Vitamin E schützt die Zellen vor schädlichen Einflüssen und unterstützt die Zellmembranen.',
      ['Pflanzenöle', 'Nüsse', 'Samen', 'Vollkorn'],
      'ca. 11–15 mg/Tag',
      'Mangel ist selten bei normaler Ernährung.',
      ['Eine Handvoll Nüsse am Tag deckt viel ab und sättigt gut.']),
    N('vitk', 'Vitamin K', '🥬', 'sage', 'Vitamin',
      'Blutgerinnung & Knochen.',
      'Vitamin K wird für die Blutgerinnung und gesunde Knochen gebraucht.',
      ['grünes Blattgemüse', 'Brokkoli', 'Spinat', 'Kohl'],
      'ca. 60–80 µg/Tag',
      'Mangel selten. Hinweis: Bei blutverdünnenden Medikamenten mit Arzt abstimmen.',
      ['Grünes Gemüse mehrmals pro Woche deckt den Bedarf locker.']),
    N('bgroup', 'B-Vitamine (B1/B2/B6)', '🌾', 'amber', 'Vitamin',
      'Energie aus dem Essen gewinnen.',
      'Die B-Vitamine helfen, aus Nahrung Energie zu gewinnen, und unterstützen Nerven und Stoffwechsel.',
      ['Vollkorn', 'Hülsenfrüchte', 'Kartoffeln', 'Eier', 'Milchprodukte'],
      'je nach Vitamin 1–2 mg/Tag',
      'Bei einseitiger Ernährung möglich: Müdigkeit, Konzentrationsprobleme.',
      ['Vollkorn statt Weißmehl liefert deutlich mehr B-Vitamine.']),
    N('folate', 'Folsäure (B9)', '🥦', 'sage', 'Vitamin',
      'Zellteilung – besonders in der Schwangerschaft.',
      'Folsäure ist wichtig für Zellteilung und Blutbildung und besonders vor/in der Schwangerschaft entscheidend.',
      ['Brokkoli', 'Spinat', 'Hülsenfrüchte', 'Vollkorn'],
      'ca. 300 µg/Tag (Schwangere mehr)',
      'Mangel kann Blutarmut verursachen; in der Schwangerschaft Risiko für das Kind.',
      ['Schwangere oder Frauen mit Kinderwunsch: ärztlich beraten lassen (oft Supplement empfohlen).']),
    N('iron', 'Eisen', '🩸', 'terracotta', 'Mineralstoff',
      'Sauerstofftransport im Blut.',
      'Eisen transportiert Sauerstoff im Blut. Pflanzliches Eisen (z. B. aus Linsen) nimmt der Körper schlechter auf als tierisches – Vitamin C hilft dabei.',
      ['Linsen', 'Bohnen', 'Haferflocken', 'Spinat', 'rotes Fleisch'],
      'Frauen ca. 15 mg, Männer ca. 10 mg/Tag',
      'Häufig bei Frauen: Müdigkeit, Blässe, Konzentrationsschwäche.',
      ['Eisen + Vitamin C kombinieren (Linsen + Paprika).', 'Kaffee & Tee hemmen die Aufnahme – erst ~1 Std. nach dem Essen trinken.']),
    N('calcium', 'Calcium', '🦴', 'peach', 'Mineralstoff',
      'Starke Knochen & Zähne.',
      'Calcium ist der wichtigste Baustein für Knochen und Zähne und wird auch für Muskeln und Nerven gebraucht.',
      ['Milch & Joghurt', 'Käse', 'grünes Gemüse', 'calciumreiches Mineralwasser'],
      'ca. 1000 mg/Tag',
      'Langfristiger Mangel schwächt die Knochen.',
      ['Wer keine Milch verträgt: grünes Gemüse + angereicherte Pflanzendrinks nutzen.', 'Vitamin D hilft, Calcium aufzunehmen.']),
    N('magnesium', 'Magnesium', '⚡', 'sage', 'Mineralstoff',
      'Muskeln, Nerven & Energie.',
      'Magnesium unterstützt Muskeln und Nerven und ist an sehr vielen Stoffwechsel-Vorgängen beteiligt.',
      ['Vollkorn', 'Nüsse', 'Hülsenfrüchte', 'Bananen', 'dunkle Schokolade'],
      'ca. 300–400 mg/Tag',
      'Möglich bei Sport/Schwitzen: Muskelkrämpfe, Müdigkeit.',
      ['Nach dem Sport hilft eine magnesiumreiche Mahlzeit (z. B. Haferflocken mit Nüssen).']),
    N('zinc', 'Zink', '🛡️', 'amber', 'Mineralstoff',
      'Immunsystem & Wundheilung.',
      'Zink unterstützt Immunsystem, Wundheilung sowie Haut und Haare.',
      ['Vollkorn', 'Hülsenfrüchte', 'Käse', 'Fleisch', 'Kürbiskerne'],
      'ca. 7–10 mg/Tag',
      'Mangel kann Immunschwäche und schlechte Wundheilung bedeuten.',
      ['Pflanzliche Quellen + tierisches Eiweiß verbessern die Aufnahme.']),
    N('iodine', 'Jod', '🧂', 'sunrise', 'Mineralstoff',
      'Schilddrüse & Stoffwechsel.',
      'Jod ist nötig für die Schilddrüsenhormone, die den ganzen Stoffwechsel steuern.',
      ['Jodsalz', 'Seefisch', 'Milchprodukte', 'Algen (vorsichtig dosieren)'],
      'ca. 200 µg/Tag',
      'Deutschland ist Jodmangel-Gebiet – Mangel kann die Schilddrüse vergrößern.',
      ['Im Haushalt Jodsalz verwenden – einfachster Schutz vor Mangel.']),
    N('omega3', 'Omega-3-Fettsäuren', '🐟', 'sage', 'Fettsäure',
      'Herz, Gehirn & Entzündungen.',
      'Omega-3-Fettsäuren unterstützen Herz und Gehirn und wirken entzündungsregulierend.',
      ['fetter Fisch (Lachs, Hering)', 'Leinöl & Leinsamen', 'Walnüsse', 'Rapsöl'],
      '1–2× fetter Fisch/Woche oder pflanzliche Quellen täglich',
      'Bei sehr fettarmer/einseitiger Kost möglich.',
      ['Vegetarisch/vegan: Leinöl, Leinsamen und Walnüsse einplanen.']),
    N('fiber', 'Ballaststoffe', '🌿', 'sage', 'Sonstiges',
      'Verdauung & lange Sättigung.',
      'Ballaststoffe halten die Verdauung in Schwung, sättigen lange und füttern die guten Darmbakterien.',
      ['Vollkorn', 'Hülsenfrüchte', 'Gemüse', 'Obst', 'Haferflocken'],
      'mind. 30 g/Tag',
      'Zu wenig führt oft zu träger Verdauung und schnellem Hunger.',
      ['Langsam steigern und genug trinken, sonst drückt der Bauch.']),
  ];

  const GKNOW = { nutrients };
  if (typeof window !== 'undefined') window.GKNOW = GKNOW;
  if (typeof module !== 'undefined' && module.exports) module.exports = GKNOW;
})(typeof window !== 'undefined' ? window : globalThis);
