/* Gesundheits-App — Inhalte: Rezepte
   © 2026 Marcel Fehse. Alle Rechte vorbehalten. */
(function (root) {
  // diet: 'vegan' | 'vegetarian' | 'meat' | 'fish'
  const R = (id, name, emoji, grad, category, diet, baseServings, prepMinutes, ingredients, steps) =>
    ({ id, name, emoji, grad, category, diet, baseServings, prepMinutes, ingredients, steps });
  const ing = (foodId, amount, unit) => ({ foodId, amount, unit });

  const recipes = [
    R('oat_bowl', 'Haferflocken-Beeren-Bowl', '🥣', 'sunrise', 'breakfast', 'vegetarian', 2, 5,
      [ing('oats', 100, 'g'), ing('milk', 300, 'ml'), ing('banana', 1, 'stueck'), ing('berries', 100, 'g')],
      ['Haferflocken mit Milch 2 Min. quellen lassen.', 'Banane in Scheiben schneiden.', 'Mit Beeren toppen.']),
    R('quark_apple', 'Magerquark mit Apfel & Hafer', '🍎', 'peach', 'breakfast', 'vegetarian', 2, 5,
      [ing('quark', 300, 'g'), ing('apple', 1, 'stueck'), ing('oats', 60, 'g')],
      ['Quark cremig rühren.', 'Apfel klein würfeln.', 'Mit Haferflocken mischen.']),
    R('scrambled', 'Rührei mit Vollkornbrot', '🍳', 'amber', 'breakfast', 'vegetarian', 2, 10,
      [ing('egg', 4, 'stueck'), ing('bread', 120, 'g'), ing('tomato', 150, 'g'), ing('oil', 10, 'ml')],
      ['Eier verquirlen, salzen.', 'In Öl bei mittlerer Hitze stocken lassen.', 'Mit Brot und Tomaten servieren.']),
    R('lentil_stew', 'Linsen-Eintopf', '🍲', 'terracotta', 'dinner', 'vegan', 2, 30,
      [ing('lentils', 150, 'g'), ing('carrot', 150, 'g'), ing('potato', 200, 'g'), ing('onion', 100, 'g'), ing('canned_tomato', 200, 'g'), ing('oil', 15, 'ml')],
      ['Zwiebel in Öl andünsten.', 'Möhren, Kartoffeln, Linsen zugeben.', 'Mit Tomaten + Wasser 25 Min. köcheln.']),
    R('chickpea_curry', 'Kichererbsen-Curry mit Reis', '🍛', 'amber', 'dinner', 'vegan', 2, 25,
      [ing('chickpeas', 240, 'g'), ing('canned_tomato', 200, 'g'), ing('onion', 100, 'g'), ing('garlic', 2, 'stueck'), ing('rice', 120, 'g'), ing('spinach', 100, 'g'), ing('oil', 15, 'ml')],
      ['Reis kochen.', 'Zwiebel + Knoblauch anbraten.', 'Kichererbsen, Tomaten, Spinat zugeben, 15 Min. köcheln.']),
    R('veggie_pasta', 'Gemüse-Nudeln', '🍝', 'sage', 'lunch', 'vegan', 2, 20,
      [ing('pasta', 160, 'g'), ing('zucchini', 200, 'g'), ing('pepper', 150, 'g'), ing('tomato', 150, 'g'), ing('garlic', 2, 'stueck'), ing('oil', 15, 'ml')],
      ['Nudeln kochen.', 'Gemüse in Öl anbraten.', 'Mit Nudeln mischen, würzen.']),
    R('potato_pan', 'Kartoffel-Gemüse-Pfanne mit Ei', '🥔', 'terracotta', 'dinner', 'vegetarian', 2, 25,
      [ing('potato', 400, 'g'), ing('pepper', 150, 'g'), ing('onion', 100, 'g'), ing('egg', 2, 'stueck'), ing('oil', 15, 'ml')],
      ['Kartoffeln würfeln, anbraten.', 'Paprika + Zwiebel zugeben.', 'Eier darüber stocken lassen.']),
    R('chicken_rice', 'Hähnchen-Reis-Pfanne', '🍗', 'amber', 'dinner', 'meat', 2, 25,
      [ing('chicken', 250, 'g'), ing('rice', 120, 'g'), ing('broccoli', 200, 'g'), ing('carrot', 100, 'g'), ing('oil', 15, 'ml')],
      ['Reis kochen.', 'Hähnchen anbraten.', 'Gemüse zugeben, garen, mischen.']),
    R('bolognese', 'Spaghetti Bolognese', '🍝', 'terracotta', 'dinner', 'meat', 2, 30,
      [ing('pasta', 160, 'g'), ing('mince', 250, 'g'), ing('canned_tomato', 200, 'g'), ing('onion', 100, 'g'), ing('carrot', 100, 'g'), ing('garlic', 2, 'stueck')],
      ['Hackfleisch anbraten.', 'Zwiebel, Möhre, Tomaten zugeben, 20 Min. köcheln.', 'Mit Nudeln servieren.']),
    R('tuna_salad', 'Thunfisch-Bohnen-Salat', '🥗', 'sage', 'lunch', 'fish', 2, 10,
      [ing('tuna', 150, 'g'), ing('beans', 240, 'g'), ing('tomato', 150, 'g'), ing('onion', 60, 'g'), ing('oil', 15, 'ml')],
      ['Bohnen abspülen.', 'Alles mischen.', 'Mit Öl, Salz, Pfeffer abschmecken.']),
    R('tofu_veg', 'Tofu-Gemüse-Reis', '🍚', 'sage', 'dinner', 'vegan', 2, 25,
      [ing('tofu', 250, 'g'), ing('rice', 120, 'g'), ing('broccoli', 200, 'g'), ing('pepper', 150, 'g'), ing('garlic', 2, 'stueck'), ing('oil', 15, 'ml')],
      ['Reis kochen.', 'Tofu würfeln, knusprig braten.', 'Gemüse zugeben, garen.']),
    R('yogurt_snack', 'Joghurt-Beeren-Becher', '🫐', 'peach', 'breakfast', 'vegetarian', 2, 5,
      [ing('yogurt', 300, 'g'), ing('berries', 120, 'g'), ing('oats', 40, 'g'), ing('walnuts', 30, 'g')],
      ['Joghurt einfüllen.', 'Beeren, Haferflocken, Nüsse darüber.']),

    // ===== Erweiterung: Frühstück =====
    R('muesli_fruit', 'Müsli mit Joghurt & Obst', '🥣', 'sunrise', 'breakfast', 'vegetarian', 2, 5,
      [ing('muesli', 100, 'g'), ing('greek_yogurt', 200, 'g'), ing('banana', 1, 'stueck'), ing('blueberry', 80, 'g')],
      ['Müsli in eine Schale geben.', 'Joghurt darüber.', 'Mit Banane und Heidelbeeren toppen.']),
    R('porridge_banana', 'Bananen-Porridge', '🍌', 'amber', 'breakfast', 'vegan', 2, 10,
      [ing('oats', 100, 'g'), ing('oat_milk', 300, 'ml'), ing('banana', 1, 'stueck'), ing('cinnamon', 2, 'g'), ing('walnuts', 30, 'g')],
      ['Haferflocken mit Haferdrink aufkochen, 5 Min. köcheln.', 'Banane zerdrücken, unterrühren.', 'Mit Zimt und Walnüssen bestreuen.']),
    R('pancakes', 'Pfannkuchen mit Banane', '🥞', 'peach', 'breakfast', 'vegetarian', 2, 15,
      [ing('flour', 150, 'g'), ing('egg', 2, 'stueck'), ing('milk', 250, 'ml'), ing('banana', 1, 'stueck')],
      ['Mehl, Eier und Milch zu einem glatten Teig rühren.', 'In etwas Öl portionsweise ausbacken.', 'Mit Bananenscheiben servieren.']),
    R('avocado_toast', 'Avocado-Brot', '🥑', 'sage', 'breakfast', 'vegan', 2, 8,
      [ing('bread', 120, 'g'), ing('avocado', 1, 'stueck'), ing('tomato', 100, 'g'), ing('lemon', 1, 'stueck')],
      ['Brot toasten.', 'Avocado zerdrücken, mit Zitrone und Salz würzen.', 'Aufs Brot streichen, mit Tomaten belegen.']),
    R('smoothie_bowl', 'Beeren-Smoothie-Bowl', '🥤', 'terracotta', 'breakfast', 'vegan', 2, 8,
      [ing('banana', 2, 'stueck'), ing('berries', 150, 'g'), ing('oat_milk', 150, 'ml'), ing('granola', 60, 'g'), ing('chia', 15, 'g')],
      ['Banane, Beeren und Haferdrink cremig mixen.', 'In eine Schale füllen.', 'Mit Granola und Chiasamen toppen.']),
    R('egg_bun', 'Ei-Brötchen', '🥚', 'amber', 'breakfast', 'vegetarian', 2, 10,
      [ing('roll', 2, 'stueck'), ing('egg', 2, 'stueck'), ing('cheese', 60, 'g'), ing('cucumber', 80, 'g')],
      ['Eier kochen oder als Spiegelei braten.', 'Brötchen aufschneiden.', 'Mit Ei, Käse und Gurke belegen.']),
    R('chia_pudding', 'Chia-Pudding', '⚫', 'sage', 'breakfast', 'vegan', 2, 5,
      [ing('chia', 40, 'g'), ing('almond_milk', 300, 'ml'), ing('banana', 1, 'stueck'), ing('raspberry', 80, 'g')],
      ['Chiasamen mit Mandeldrink verrühren.', 'Über Nacht im Kühlschrank quellen lassen.', 'Mit Banane und Himbeeren servieren.']),
    R('cheese_bread', 'Käsebrot mit Tomate', '🧀', 'peach', 'breakfast', 'vegetarian', 2, 5,
      [ing('bread', 120, 'g'), ing('cheese', 80, 'g'), ing('tomato', 100, 'g'), ing('butter', 20, 'g')],
      ['Brot mit Butter bestreichen.', 'Mit Käse belegen.', 'Tomatenscheiben darauf, würzen.']),
    R('quark_berries', 'Quark mit Beeren & Honig', '🍯', 'sunrise', 'breakfast', 'vegetarian', 2, 5,
      [ing('quark', 250, 'g'), ing('berries', 120, 'g'), ing('honey', 20, 'g'), ing('almonds', 30, 'g')],
      ['Quark cremig rühren.', 'Beeren unterheben.', 'Mit Honig und gehackten Mandeln toppen.']),
    R('scrambled_spinach', 'Rührei mit Spinat', '🍳', 'sage', 'breakfast', 'vegetarian', 2, 12,
      [ing('egg', 4, 'stueck'), ing('spinach', 100, 'g'), ing('bread', 100, 'g'), ing('oil', 10, 'ml')],
      ['Spinat in Öl kurz andünsten.', 'Verquirlte Eier zugeben, stocken lassen.', 'Mit Brot servieren.']),
    R('overnight_oats', 'Overnight Oats', '🥣', 'amber', 'breakfast', 'vegetarian', 2, 5,
      [ing('oats', 100, 'g'), ing('milk', 250, 'ml'), ing('chia', 15, 'g'), ing('apple', 1, 'stueck'), ing('cinnamon', 2, 'g')],
      ['Haferflocken, Milch und Chia verrühren.', 'Über Nacht kühl quellen lassen.', 'Mit geraspeltem Apfel und Zimt servieren.']),
    R('peanut_toast', 'Erdnussbutter-Bananen-Toast', '🥜', 'terracotta', 'breakfast', 'vegan', 2, 5,
      [ing('toast', 100, 'g'), ing('peanut_butter', 40, 'g'), ing('banana', 1, 'stueck')],
      ['Toast rösten.', 'Mit Erdnussbutter bestreichen.', 'Bananenscheiben darauflegen.']),

    // ===== Erweiterung: Mittag =====
    R('greek_salad', 'Griechischer Salat', '🥗', 'sage', 'lunch', 'vegetarian', 2, 15,
      [ing('cucumber', 200, 'g'), ing('tomato', 200, 'g'), ing('feta', 100, 'g'), ing('olives', 50, 'g'), ing('onion', 60, 'g'), ing('oil', 15, 'ml')],
      ['Gurke und Tomaten würfeln.', 'Zwiebel in Ringe schneiden.', 'Mit Feta, Oliven und Öl mischen.']),
    R('couscous_salad', 'Couscous-Salat', '🥗', 'amber', 'lunch', 'vegan', 2, 15,
      [ing('couscous', 150, 'g'), ing('pepper', 150, 'g'), ing('cucumber', 150, 'g'), ing('tomato', 150, 'g'), ing('lemon', 1, 'stueck'), ing('oil', 15, 'ml')],
      ['Couscous mit kochendem Wasser übergießen, quellen lassen.', 'Gemüse klein würfeln.', 'Alles mit Zitrone und Öl mischen.']),
    R('wrap_chicken', 'Hähnchen-Wrap', '🌯', 'terracotta', 'lunch', 'meat', 2, 20,
      [ing('tortilla_wrap', 2, 'stueck'), ing('chicken', 200, 'g'), ing('lettuce', 80, 'g'), ing('tomato', 100, 'g'), ing('yogurt', 80, 'g')],
      ['Hähnchen würzen und anbraten.', 'Wraps mit Joghurt bestreichen.', 'Mit Salat, Tomate und Hähnchen füllen, einrollen.']),
    R('lentil_salad', 'Linsensalat', '🫘', 'sage', 'lunch', 'vegan', 2, 25,
      [ing('lentils', 150, 'g'), ing('carrot', 100, 'g'), ing('pepper', 100, 'g'), ing('onion', 60, 'g'), ing('oil', 15, 'ml'), ing('lemon', 1, 'stueck')],
      ['Linsen weich kochen, abkühlen lassen.', 'Gemüse fein würfeln.', 'Mit Öl, Zitrone, Salz und Pfeffer abschmecken.']),
    R('caprese', 'Tomate-Mozzarella', '🍅', 'peach', 'lunch', 'vegetarian', 2, 10,
      [ing('tomato', 250, 'g'), ing('mozzarella', 150, 'g'), ing('basil', 10, 'g'), ing('oil', 15, 'ml')],
      ['Tomaten und Mozzarella in Scheiben schneiden.', 'Abwechselnd anrichten.', 'Mit Basilikum, Öl, Salz und Pfeffer servieren.']),
    R('tuna_sandwich', 'Thunfisch-Sandwich', '🥪', 'amber', 'lunch', 'fish', 2, 10,
      [ing('bread', 120, 'g'), ing('tuna', 120, 'g'), ing('cucumber', 80, 'g'), ing('lettuce', 40, 'g'), ing('mayo', 20, 'g')],
      ['Thunfisch mit Mayonnaise verrühren.', 'Brot belegen.', 'Mit Gurke und Salat zusammenklappen.']),
    R('quinoa_bowl', 'Quinoa-Gemüse-Bowl', '🥙', 'terracotta', 'lunch', 'vegan', 2, 25,
      [ing('quinoa', 150, 'g'), ing('chickpeas', 200, 'g'), ing('pepper', 100, 'g'), ing('cucumber', 100, 'g'), ing('oil', 15, 'ml')],
      ['Quinoa garen.', 'Kichererbsen abspülen, Gemüse würfeln.', 'Alles in einer Schale anrichten, mit Öl beträufeln.']),
    R('fried_rice', 'Gebratener Reis mit Ei', '🍚', 'sage', 'lunch', 'vegetarian', 2, 20,
      [ing('rice', 150, 'g'), ing('egg', 2, 'stueck'), ing('peas', 100, 'g'), ing('carrot', 100, 'g'), ing('soy_sauce', 20, 'ml')],
      ['Reis kochen, abkühlen lassen.', 'Gemüse anbraten, Ei dazugeben.', 'Reis und Sojasauce unterrühren, kräftig anbraten.']),
    R('caesar_salad', 'Caesar Salad', '🥗', 'amber', 'lunch', 'meat', 2, 20,
      [ing('lettuce', 150, 'g'), ing('chicken', 200, 'g'), ing('parmesan', 40, 'g'), ing('bread', 80, 'g')],
      ['Hähnchen braten, in Streifen schneiden.', 'Brot würfeln, knusprig rösten (Croutons).', 'Salat mit Hähnchen, Croutons und Parmesan anrichten.']),
    R('omelette', 'Gemüse-Omelett', '🍳', 'peach', 'lunch', 'vegetarian', 2, 12,
      [ing('egg', 4, 'stueck'), ing('pepper', 100, 'g'), ing('mushrooms', 100, 'g'), ing('cheese', 50, 'g'), ing('oil', 10, 'ml')],
      ['Gemüse klein schneiden und andünsten.', 'Verquirlte Eier zugeben.', 'Mit Käse bestreuen, zusammenklappen.']),
    R('hummus_bowl', 'Hummus-Bowl mit Pita', '🥣', 'sunrise', 'lunch', 'vegan', 2, 10,
      [ing('hummus', 150, 'g'), ing('pita', 2, 'stueck'), ing('cucumber', 100, 'g'), ing('tomato', 100, 'g'), ing('olives', 40, 'g')],
      ['Pita-Brote kurz aufbacken.', 'Hummus in eine Schale geben.', 'Mit Gurke, Tomate und Oliven anrichten.']),
    R('potato_salad', 'Kartoffelsalat', '🥔', 'terracotta', 'lunch', 'vegetarian', 2, 30,
      [ing('potato', 400, 'g'), ing('egg', 2, 'stueck'), ing('cucumber', 100, 'g'), ing('yogurt', 100, 'g'), ing('onion', 50, 'g')],
      ['Kartoffeln kochen, abkühlen, würfeln.', 'Eier hart kochen, würfeln.', 'Mit Gurke, Joghurt und Zwiebel vermengen, abschmecken.']),
    R('salmon_salad', 'Lachs-Salat', '🐟', 'sage', 'lunch', 'fish', 2, 20,
      [ing('salmon', 200, 'g'), ing('lettuce', 120, 'g'), ing('tomato', 100, 'g'), ing('avocado', 1, 'stueck'), ing('lemon', 1, 'stueck')],
      ['Lachs braten oder dünsten.', 'Salat, Tomate und Avocado anrichten.', 'Lachs darauf, mit Zitrone beträufeln.']),
    R('bean_wrap', 'Bohnen-Wrap', '🌯', 'amber', 'lunch', 'vegan', 2, 15,
      [ing('tortilla_wrap', 2, 'stueck'), ing('beans', 200, 'g'), ing('corn', 100, 'g'), ing('pepper', 100, 'g'), ing('salsa', 40, 'g')],
      ['Bohnen abspülen.', 'Mit Mais, Paprika und Salsa mischen.', 'In die Wraps füllen und einrollen.']),

    // ===== Erweiterung: Abend =====
    R('spaghetti_aglio', 'Spaghetti Aglio e Olio', '🍝', 'amber', 'dinner', 'vegan', 2, 15,
      [ing('pasta', 200, 'g'), ing('garlic', 3, 'stueck'), ing('oil', 30, 'ml'), ing('chili', 10, 'g'), ing('parsley', 10, 'g')],
      ['Nudeln kochen.', 'Knoblauch und Chili in Öl sanft anbraten.', 'Nudeln untermischen, mit Petersilie servieren.']),
    R('salmon_veg', 'Lachs mit Ofengemüse', '🐟', 'terracotta', 'dinner', 'fish', 2, 30,
      [ing('salmon', 250, 'g'), ing('broccoli', 200, 'g'), ing('potato', 300, 'g'), ing('lemon', 1, 'stueck'), ing('oil', 15, 'ml')],
      ['Kartoffeln und Brokkoli mit Öl im Ofen rösten.', 'Lachs würzen und mitgaren.', 'Mit Zitrone beträufeln.']),
    R('veggie_curry', 'Süßkartoffel-Curry', '🍛', 'sunrise', 'dinner', 'vegan', 2, 30,
      [ing('sweet_potato', 300, 'g'), ing('chickpeas', 200, 'g'), ing('coconut_milk', 200, 'ml'), ing('spinach', 100, 'g'), ing('rice', 120, 'g'), ing('curry_powder', 10, 'g')],
      ['Reis kochen.', 'Süßkartoffel würfeln, mit Curry anbraten.', 'Kokosmilch, Kichererbsen und Spinat zugeben, köcheln.']),
    R('stuffed_peppers', 'Gefüllte Paprika', '🫑', 'peach', 'dinner', 'vegetarian', 2, 40,
      [ing('pepper', 300, 'g'), ing('rice', 120, 'g'), ing('cheese', 60, 'g'), ing('canned_tomato', 200, 'g'), ing('onion', 80, 'g')],
      ['Reis vorkochen, mit Zwiebel mischen.', 'Paprika füllen, mit Käse bestreuen.', 'In Tomatensauce im Ofen 30 Min. backen.']),
    R('frittata', 'Kartoffel-Frittata', '🍳', 'sage', 'dinner', 'vegetarian', 2, 30,
      [ing('egg', 5, 'stueck'), ing('potato', 300, 'g'), ing('onion', 80, 'g'), ing('cheese', 60, 'g'), ing('oil', 15, 'ml')],
      ['Kartoffeln und Zwiebel anbraten.', 'Verquirlte Eier mit Käse zugeben.', 'Stocken lassen, dann im Ofen fertig backen.']),
    R('chili_con_carne', 'Chili con Carne', '🌶️', 'terracotta', 'dinner', 'meat', 2, 35,
      [ing('mince', 250, 'g'), ing('beans', 200, 'g'), ing('canned_tomato', 200, 'g'), ing('corn', 100, 'g'), ing('onion', 100, 'g'), ing('rice', 120, 'g')],
      ['Hackfleisch und Zwiebel anbraten.', 'Tomaten, Bohnen und Mais zugeben, 25 Min. köcheln.', 'Mit Reis servieren.']),
    R('fish_potato', 'Backfisch mit Kartoffeln', '🐟', 'amber', 'dinner', 'fish', 2, 30,
      [ing('cod', 250, 'g'), ing('potato', 350, 'g'), ing('lemon', 1, 'stueck'), ing('oil', 15, 'ml')],
      ['Kartoffeln als Spalten im Ofen rösten.', 'Kabeljau würzen und garen.', 'Mit Zitrone servieren.']),
    R('tofu_stirfry', 'Tofu-Pfanne', '🍜', 'sage', 'dinner', 'vegan', 2, 25,
      [ing('tofu', 250, 'g'), ing('broccoli', 200, 'g'), ing('pepper', 150, 'g'), ing('soy_sauce', 20, 'ml'), ing('rice', 120, 'g')],
      ['Reis kochen.', 'Tofu würfeln und knusprig braten.', 'Gemüse zugeben, mit Sojasauce ablöschen.']),
    R('pork_veg', 'Schweinefilet mit Gemüse', '🥩', 'terracotta', 'dinner', 'meat', 2, 30,
      [ing('pork', 250, 'g'), ing('zucchini', 200, 'g'), ing('potato', 300, 'g'), ing('oil', 15, 'ml')],
      ['Kartoffeln kochen oder rösten.', 'Schweinefilet anbraten und ruhen lassen.', 'Zucchini anbraten, alles zusammen servieren.']),
    R('veggie_lasagne', 'Gemüse-Lasagne', '🍝', 'peach', 'dinner', 'vegetarian', 2, 45,
      [ing('lasagne', 150, 'g'), ing('zucchini', 200, 'g'), ing('canned_tomato', 250, 'g'), ing('cheese', 80, 'g'), ing('onion', 80, 'g')],
      ['Zucchini und Zwiebel in Tomatensauce dünsten.', 'Lasagneplatten und Sauce schichten.', 'Mit Käse bestreuen, 30 Min. backen.']),
    R('shrimp_pasta', 'Garnelen-Pasta', '🍤', 'amber', 'dinner', 'fish', 2, 20,
      [ing('pasta', 200, 'g'), ing('shrimp', 200, 'g'), ing('garlic', 3, 'stueck'), ing('tomato', 150, 'g'), ing('oil', 20, 'ml')],
      ['Nudeln kochen.', 'Garnelen mit Knoblauch in Öl anbraten.', 'Tomaten zugeben, mit Nudeln mischen.']),
    R('ratatouille', 'Ratatouille', '🍆', 'sage', 'dinner', 'vegan', 2, 35,
      [ing('eggplant', 200, 'g'), ing('zucchini', 200, 'g'), ing('pepper', 150, 'g'), ing('tomato', 200, 'g'), ing('onion', 80, 'g'), ing('oil', 20, 'ml')],
      ['Gemüse in Würfel schneiden.', 'Zwiebel anbraten, restliches Gemüse zugeben.', 'Mit Tomaten 25 Min. schmoren.']),
    R('turkey_rice', 'Putengeschnetzeltes mit Reis', '🍗', 'terracotta', 'dinner', 'meat', 2, 25,
      [ing('turkey', 250, 'g'), ing('rice', 120, 'g'), ing('mushrooms', 150, 'g'), ing('cream', 100, 'ml'), ing('onion', 80, 'g')],
      ['Reis kochen.', 'Pute und Zwiebel anbraten, Pilze zugeben.', 'Mit Sahne ablöschen, kurz köcheln.']),
    R('baked_potato', 'Ofenkartoffel mit Kräuterquark', '🥔', 'sunrise', 'dinner', 'vegetarian', 2, 50,
      [ing('potato', 500, 'g'), ing('quark', 250, 'g'), ing('chives', 10, 'g'), ing('butter', 20, 'g')],
      ['Kartoffeln im Ofen weich backen.', 'Quark mit Schnittlauch und Salz verrühren.', 'Kartoffeln aufschneiden, mit Butter und Quark füllen.'])
  ];

  root.GCPARTS = root.GCPARTS || {};
  root.GCPARTS.recipes = recipes;
  if (typeof module !== 'undefined' && module.exports) module.exports = recipes;
})(typeof window !== 'undefined' ? window : globalThis);
